spring:
  application:
    name: user-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://ims-discovery-server.herokuapp.com/eureka/
  instance:
    hostname: ims-discovery-server.herokuapp.com
    homePageUrl: https://ims-user-service.herokuapp.com/
    statusPageUrl: https://ims-user-service.herokuapp.com/actuator/info
    healthCheckUrl: https://ims-user-service.herokuapp.com/actuator/health